language: generic 
sudo: required
services: 
  - docker

before_install:
  - docker build -t eagerstudent/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true eagerstudent/docker-react npm run test

deploy:
  edge: true
  provider: elasticbeanstalk
  region: "eu-central-1"
  app: "docker"
  env: "Docker-env"
  bucket_name: "elasticbeanstalk-eu-central-1-554495121728"
  bucket_path: "docker"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY

